name: Action
on:
  pull_request: # When a PR is opened, edited, updated, or a label is added.
    types: [opened, synchronize, labeled, edited]
  push:
    branches:
      - master # Every time a PR is merged to master.

jobs:
  test:
    name: "Manage labels and assignees"
    runs-on: ubuntu-latest
    steps:
      - name: Get result
        run: echo &ENV
