name: Action
on:
  pull_request: # When a PR is opened, edited, updated, or a label is added.
    types: [opened, synchronize, labeled, edited]
  push:
    branches:
      - master # Every time a PR is merged to master.

jobs:
  build:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - name: test
        timeout-minutes: 1
        run: |
          while true; do echo 1; sleep 1; done

      - name: run-always-step
        if: ${{ always() }}
        run: |
          echo "run-always-step"
          echo "${{ job.status }}"

  run-always-job:
    if: ${{ always() }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: run-always-job
        run: |
          echo "run-always-job"
          echo "${{ needs.build.result }}"
